site_name: FlectoneChat Docs
theme:
  features:
    - content.code.annotate
    - navigation.instant
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue
plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        ru:
          name: Русский
          build: true
extra:
  generator: false

markdown_extensions:
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 - 2023 Flectone

extra_css: [css/extra.css]
