#  █▀ █   ██▀ ▄▀▀ ▀█▀ ▄▀▄ █▄ █ ██▀ ▄▀▀ █▄█ ▄▀▄ ▀█▀
#  █▀ █▄▄ █▄▄ ▀▄▄  █  ▀▄▀ █ ▀█ █▄▄ ▀▄▄ █ █ █▀█  █
language: en

# This is &&1
color.first: "#1abaf0"
# This is &&2
color.second: "#77d7f7"

tab.header.enable: true
tab.footer.enable: true

color.worlds.enable: true
color.worlds.team.enable: true
color.normal: "#4eff52● &f"
color.nether: "#ff4e4e● &f"
color.the_end: "#834eff● &f"
color.custom: "#1abaf0● &f"

server.motd.enable: true
server.online.enable: true
server.online.number: 69

chat.ping.prefix: "@"
chat.no_recipients.enable: true
chat.color.url: "&&1"
chat.color.tooltip: "&&2[<tooltip>]"

afk.suffix: " #f2d40f💤"
afk.timeout.enable: true
afk.timeout.time: 3000

## █ █ ▄▀▄ █ █ █   ▀█▀   ▄▀▄ █▀▄ █
## ▀▄▀ █▀█ ▀▄█ █▄▄  █    █▀█ █▀  █
# if off, first flectonechat symbols and then vault symbols
# if on, first vault symbols and then vault symbols
vault.symbols_first: false
vault.prefix: "<vault_prefix>"
vault.suffix: "<vault_suffix>"

tab.update.enable: true
# is specified in seconds
tab.update.rate: 2

chat.locale.range: 100
chat.locale.message: "&&1<player>&&2: <message>"
# if enabled, messages from local chat will be cancelled for other plugins
chat.locale.set_cancelled: true

chat.global.prefix: "!"
chat.global.message: "&&1<player>&&2 » <message>"
chat.global.clear_prefix: true
chat.global.enable: true

stream.prefix: "#ff4e4e⏻ "

ping.bad.color: "#ff4e4e"
ping.bad.count: 200
ping.medium.color: "#fce303"
ping.medium.count: 100
ping.good.color: "#4eff52"

mark.enable: true
mark.item: "WOODEN_SWORD"
mark.range: 30

helper.see.permission: "flectonechat.helpersee"

stream.global: true
me.global: true
try.global: true
try-cube.global: true

try-cube.max_amount: 9
try-cube.6: "⚅"
try-cube.5: "⚄"
try-cube.4: "⚃"
try-cube.3: "⚂"
try-cube.2: "⚁"
try-cube.1: "⚀"

cooldown.enable: false

chatping.sound.enable: true
chatping.sound.type: "BLOCK_NOTE_BLOCK_HARP"

join.sound.enable: false
join.sound.type: "BLOCK_NOTE_BLOCK_BELL"

quit.sound.enable: false
quit.sound.type: "BLOCK_NOTE_BLOCK_BELL"

localechat.sound.enable: false
localechat.sound.type: "BLOCK_NOTE_BLOCK_BELL"
localechat.cooldown.enable: true
localechat.cooldown.time: 5
localechat.cooldown.permission: "flectonechat.localechat.cooldown.immune"

globalchat.sound.enable: false
globalchat.sound.type: "BLOCK_NOTE_BLOCK_BELL"
globalchat.cooldown.enable: true
globalchat.cooldown.time: 5
globalchat.cooldown.permission: "flectonechat.globalchat.cooldown.immune"

chatcolor.sound.enable: false
chatcolor.sound.type: "BLOCK_NOTE_BLOCK_BELL"
chatcolor.cooldown.enable: false
chatcolor.cooldown.time: 5
chatcolor.cooldown.permission: "flectonechat.chatcolor.cooldown.immune"

flectonechat.sound.enable: true
flectonechat.sound.type: "BLOCK_NOTE_BLOCK_BELL"
flectonechat.cooldown.enable: false
flectonechat.cooldown.time: 5
flectonechat.cooldown.permission: "flectonechat.flectonechat.cooldown.immune"

ignore.sound.enable: false
ignore.sound.type: "BLOCK_NOTE_BLOCK_BELL"
ignore.cooldown.enable: false
ignore.cooldown.time: 5
ignore.cooldown.permission: "flectonechat.ignore.cooldown.immune"

ignore-list.sound.enable: false
ignore-list.sound.type: "BLOCK_NOTE_BLOCK_BELL"
ignore-list.cooldown.enable: false
ignore-list.cooldown.time: 5
ignore-list.cooldown.permission: "flectonechat.ignore-list.cooldown.immune"

mail.sound.enable: false
mail.sound.type: "BLOCK_NOTE_BLOCK_BELL"
mail.cooldown.enable: true
mail.cooldown.time: 5
mail.cooldown.permission: "flectonechat.mail.cooldown.immune"

helper.sound.enable: true
helper.sound.type: "BLOCK_NOTE_BLOCK_BELL"
helper.cooldown.enable: true
helper.cooldown.time: 5
helper.cooldown.permission: "flectonechat.mail.cooldown.immune"

mark.sound.enable: false
mark.sound.type: "BLOCK_NOTE_BLOCK_BELL"
mark.cooldown.enable: true
mark.cooldown.time: 5
mark.cooldown.permission: "flectonechat.mark.cooldown.immune"

me.sound.enable: false
me.sound.type: "BLOCK_NOTE_BLOCK_BELL"
me.cooldown.enable: true
me.cooldown.time: 5
me.cooldown.permission: "flectonechat.me.cooldown.immune"

msg.sound.enable: false
msg.sound.type: "BLOCK_NOTE_BLOCK_BELL"
msg.cooldown.enable: false
msg.cooldown.time: 5
msg.cooldown.permission: "flectonechat.msg.cooldown.immune"

ping.sound.enable: true
ping.sound.type: "BLOCK_NOTE_BLOCK_BELL"
ping.cooldown.enable: false
ping.cooldown.time: 5
ping.cooldown.permission: "flectonechat.ping.cooldown.immune"

reply.sound.enable: false
reply.sound.type: "BLOCK_NOTE_BLOCK_BELL"
reply.cooldown.enable: true
reply.cooldown.time: 5
reply.cooldown.permission: "flectonechat.reply.cooldown.immune"

mail-clear.sound.enable: false
mail-clear.sound.type: "BLOCK_NOTE_BLOCK_BELL"
mail-clear.cooldown.enable: false
mail-clear.cooldown.time: 5
mail-clear.cooldown.permission: "flectonechat.mail-clear.cooldown.immune"

stream.sound.enable: true
stream.sound.type: "BLOCK_NOTE_BLOCK_BELL"
stream.cooldown.enable: true
stream.cooldown.time: 5
stream.cooldown.permission: "flectonechat.stream.cooldown.immune"

try.sound.enable: false
try.sound.type: "BLOCK_NOTE_BLOCK_BELL"
try.cooldown.enable: true
try.cooldown.time: 5
try.cooldown.permission: "flectonechat.try.cooldown.immune"

try-cube.sound.enable: false
try-cube.sound.type: "BLOCK_NOTE_BLOCK_BELL"
try-cube.cooldown.enable: true
try-cube.cooldown.time: 5
try-cube.cooldown.permission: "flectonechat.try-cube.cooldown.immune"

afk.sound.enable: false
afk.sound.type: "BLOCK_NOTE_BLOCK_BELL"
afk.cooldown.enable: false
afk.cooldown.time: 5
afk.cooldown.permission: "flectonechat.afk.cooldown.immune"

mute.sound.enable: true
mute.sound.type: "BLOCK_NOTE_BLOCK_BELL"
mute.cooldown.enable: false
mute.cooldown.time: 5
mute.cooldown.permission: "flectonechat.mute.cooldown.immune"

unmute.sound.enable: false
unmute.sound.type: "BLOCK_NOTE_BLOCK_BELL"
unmute.cooldown.enable: false
unmute.cooldown.time: 5
unmute.cooldown.permission: "flectonechat.mute.cooldown.immune"