#  █▀ █   ██▀ ▄▀▀ ▀█▀ ▄▀▄ █▄ █ ██▀ ▄▀▀ █▄█ ▄▀▄ ▀█▀
#  █▀ █▄▄ █▄▄ ▀▄▄  █  ▀▄▀ █ ▀█ █▄▄ ▀▄▄ █ █ █▀█  █
language: en

# This is &&1
color.first: "#1abaf0"
# This is &&2
color.second: "#77d7f7"

tab.header.enable: true
tab.footer.enable: true

color.worlds.enable: true
color.normal: "#4eff52"
color.nether: "#ff4e4e"
color.the_end: "#834eff"
color.custom: "#1abaf0"

server.motd.enable: true
server.online.enable: true
server.online.number: 69

chat.ping.prefix: "@"
chat.no_recipients.enable: true
chat.color.url: "&&1"
chat.color.tooltip: "&&2[<tooltip>]"

## █ █ ▄▀▄ █ █ █   ▀█▀   ▄▀▄ █▀▄ █
## ▀▄▀ █▀█ ▀▄█ █▄▄  █    █▀█ █▀  █
vault.prefix: "<vault_prefix>"
vault.suffix: "<vault_suffix>"

tab.update: true
# is specified in seconds
tab.update.rate: 2

chat.locale.range: 100
chat.locale.message: "&&1<player>&&2: "

chat.global.prefix: "!"
chat.global.message: "&&1<player>&&2 » "
chat.global.enable: true

stream.prefix: "#ff4e4e⏻ "

ping.bad.color: "#ff4e4e"
ping.bad.count: 200
ping.medium.color: "#fce303"
ping.medium.count: 100
ping.good.color: "#4eff52"

mark.enable: true
mark.item: "WOODEN_SWORD"
mark.range: 30

try-cube.max_amount: 10
try-cube.6: "⚅"
try-cube.5: "⚄"
try-cube.4: "⚃"
try-cube.3: "⚂"
try-cube.2: "⚁"
try-cube.1: "⚀"

