#  █▀ █   ██▀ ▄▀▀ ▀█▀ ▄▀▄ █▄ █ ██▀ ▄▀▀ █▄█ ▄▀▄ ▀█▀
#  █▀ █▄▄ █▄▄ ▀▄▄  █  ▀▄▀ █ ▀█ █▄▄ ▀▄▄ █ █ █▀█  █
version: "3.10.0"

language: en
database: "database"

scoreboard:
  custom: false

color:
  # &&1
  first: "#1abaf0"

  # &&2
  second: "#77d7f7"

tab:
  header-message:
    enable: true
  footer-message:
    enable: true
  update:
    enable: true

    # minecraft ticks (1sec = 20ticks)
    rate: 40
  player-ping:
    enable: true

server:
  brand:
    enable: true

    update:
      enable: true
      rate: 20

  motd:
    messages:
      enable: true
  online:
    count:
      enable: true
      digit: 69
  icon:
    enable: true
    # Modes: single or random
    mode: random

    # If "single" mode is enabled, only the first one will be displayed
    names:
      - "server-icon-1"
      - "server-icon-2"

chat:
  bubble:
    enable: true
    max-per-line: 35
    read-speed: 800

  local:
    range: 100
    set-cancelled: true
    no-recipients:
      enable: true

  global:
    enable: true
    prefix:
      cleared: true

    set-cancelled: false

  patterns:
    - ":) , ☺"
    - ":D , ☻"
    - ":( , ☹"
    - ":ok: , 🖒"
    - ":+1: , 🖒"
    - ":-1: , 🖓"
    - ":cool: , 😎"
    - "B) , 😎"
    - ":clown: , 🤡"
    - "<3 , ❤"
    - "xd , 😆"
    - "%) , 😵"
    - "=D , 😃"
    - ">:( , 😡"
    - ":idk: , ¯\\_(ツ)_/¯"
    - ":angry: , (╯°□°)╯︵ ┻━┻"
    - ":happy: , ＼(＾O＾)／"

  cords:
    enable: true
  stats:
    enable: true
  hide:
    enable: true
  url:
    enable: true
  tooltip:
    enable: true
  ping:
    enable: true

death:
  message:
    enable: true

    # if disabled, custom death messages will not be shown
    visible: true

    # if enabled, then death from any mob will be located on the "death.mob.default",
    # otherwise it will be necessary to register for each separately
    mob-default: true

advancement:
  message:
    enable: true

    task:
      visible: true
    goal:
      visible: true
    challenge:
      visible: true


player:
  display-name: "<world_prefix><vault_prefix><stream_prefix><player><afk_suffix><vault_suffix>"
  tab-name: "<world_prefix><vault_prefix><stream_prefix><player><afk_suffix><vault_suffix>"

  world:
    # type or name
    # if mode=name the language file should contain lines with names of the worlds
    mode: "type"
    prefix:
      enable: true

  name-tag:
    enable: true

  name-visible: false

  item:
    sign:
      enable: true

  join:
    message:
      enable: true

  quit:
    message:
      enable: true

command:
  afk:
    enable: true
    timeout:
      enable: true
      time: 3000

  warn:
    enable: true
    announce: true
    count-for-ban: 3

  warnlist:
    enable: true
    per-page: 4

  unwarn:
    enable: true

  spy:
    enable: true

  ball:
    enable: true
    global: true

  banlist:
    enable: true
    per-page: 4

  broadcast:
    enable: true

  switch-chat:
    enable: true

  chat-settings:
    enable: true

  chatcolor:
    enable: true

  clear-chat:
    enable: true

  firstonline:
    enable: true

  flectonechat:
    enable: true

  helper:
    enable: true
    see:
      permission: "flectonechat.helpersee"

  ignore:
    enable: true

  ignorelist:
    enable: true
    per-page: 4

  last-online:
    enable: true

  mail:
    enable: true

  mail-clear:
    enable: true

  maintenance:
    enable: true
    permission: "flectonechat.maintenance"
    turn-on: false

  mark:
    enable: true
    item: "WOODEN_SWORD"
    range: 30

  me:
    enable: true
    global: true

  msg:
    enable: true

  mute:
    enable: true
    announce: true

  mutelist:
    enable: true
    per-page: 4

  ping:
    enable: true
    bad:
      color: "#ff4e4e"
      count: 200
    medium:
      color: "#fce303"
      count: 100
    good:
      color: "#4eff52"

  poll:
    enable: true
    time: 50
    permission: "flectonechat.pollcreate"

  reply:
    enable: true

  stream:
    enable: true
    global: true

    offline-prefix:
      enable: true

  tempban:
    enable: true
    announce: true

  tic-tac-toe:
    enable: true

  try:
    enable: true
    global: true

  try-cube:
    enable: true
    global: true
    max-amount: 9

  unban:
    enable: true

  unmute:
    enable: true

cool-down:
  enable: false

  warn:
    enable: false
    time: 5
    permission: "flectonechat.warn.cooldown.immune"
  unwarn:
    enable: false
    time: 5
    permission: "flectonechat.unwarn.cooldown.immune"
  warnlist:
    enable: false
    time: 5
    permission: "flectonechat.warnlist.cooldown.immune"
  spy:
    enable: false
    time: 5
    permission: "flectonechat.spy.cooldown.immune"
  poll:
    enable: false
    time: 5
    permission: "flectonechat.poll.cooldown.immune"
  broadcast:
    enable: false
    time: 5
    permission: "flectonechat.broadcast.cooldown.immune"
  unban:
    enable: false
    permission: "flectonechat.ban.cooldown.immune"
  tempban:
    enable: false
    time: 5
    permission: "flectonechat.ban.cooldown.immune"
  clear-chat:
    enable: true
    time: 5
    permission: "flectonechat.clear-chat.cooldown.immune"
  switch-chat:
    enable: true
    time: 5
    permission: "flectonechat.switch-chat.cooldown.immune"
  chat-settings:
    enable: true
    time: 5
    permission: "flectonechat.chat-settings.cooldown.immune"
  localchat:
    enable: true
    time: 5
    permission: "flectonechat.localchat.cooldown.immune"
  globalchat:
    enable: true
    time: 5
    permission: "flectonechat.globalchat.cooldown.immune"
  chatcolor:
    enable: false
    time: 5
    permission: "flectonechat.chatcolor.cooldown.immune"
  flectonechat:
    enable: false
    time: 5
    permission: "flectonechat.flectonechat.cooldown.immune"
  ignore:
    enable: false
    time: 5
    permission: "flectonechat.ignore.cooldown.immune"
  ignorelist:
    enable: false
    time: 5
    permission: "flectonechat.ignorelist.cooldown.immune"
  mail:
    enable: true
    time: 5
    permission: "flectonechat.mail.cooldown.immune"
  helper:
    enable: true
    time: 5
    permission: "flectonechat.helper.cooldown.immune"
  mark:
    enable: false
    time: 5
    permission: "flectonechat.mark.cooldown.immune"
  me:
    enable: true
    time: 5
    permission: "flectonechat.me.cooldown.immune"
  msg:
    enable: false
    time: 5
    permission: "flectonechat.msg.cooldown.immune"
  ping:
    enable: false
    time: 5
    permission: "flectonechat.ping.cooldown.immune"
  reply:
    enable: false
    time: 5
    permission: "flectonechat.reply.cooldown.immune"
  mail-clear:
    enable: false
    time: 5
    permission: "flectonechat.mail-clear.cooldown.immune"
  stream:
    enable: false
    time: 5
    permission: "flectonechat.stream.cooldown.immune"
  try:
    enable: true
    time: 5
    permission: "flectonechat.try.cooldown.immune"
  try-cube:
    enable: true
    time: 5
    permission: "flectonechat.try-cube.cooldown.immune"
  afk:
    enable: false
    time: 5
    permission: "flectonechat.afk.cooldown.immune"
  mute:
    enable: false
    time: 5
    permission: "flectonechat.mute.cooldown.immune"
  unmute:
    enable: false
    time: 5
    permission: "flectonechat.mute.cooldown.immune"
  maintenance:
    enable: false
    time: 5
    permission: "flectonechat.maintenance.cooldown.immune"
  ball:
    enable: false
    time: 5
    permission: "flectonechat.ball.cooldown.immune"
  tic-tac-toe:
    enable: false
    time: 5
    permission: "flectonechat.tic-tac-toe.cooldown.immune"
  banlist:
    enable: false
    time: 5
    permission: "flectonechat.banlist.cooldown.immune"
  mutelist:
    enable: false
    time: 5
    permission: "flectonechat.mutelist.cooldown.immune"

sound:
  warn:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  unwarn:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  warnlist:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  spy:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  poll:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  broadcast:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  unban:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  tempban:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  clear-chat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  switch-chat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  chat-settings:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  localchat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  globalchat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  chatping:
    enable: true
    type: "BLOCK_NOTE_BLOCK_HARP"
  join:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  quit:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  chatcolor:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  flectonechat:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  ignore:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  ignorelist:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  mail:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  helper:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  mark:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  me:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  msg:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  ping:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  reply:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  mail-clear:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  stream:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  try:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  try-cube:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  afk:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  mute:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  unmute:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  maintenance:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL"
  ball:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"
  tic-tac-toe:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL"