#  █▀ █   ██▀ ▄▀▀ ▀█▀ ▄▀▄ █▄ █ ██▀ ▄▀▀ █▄█ ▄▀▄ ▀█▀
#  █▀ █▄▄ █▄▄ ▀▄▄  █  ▀▄▀ █ ▀█ █▄▄ ▀▄▄ █ █ █▀█  █
#
# Check our wiki
# https://chat.flectone.net

version: "3.11.1"
database: "database"
language: en

scoreboard:
  custom: false

color:
  # &&1
  first: "#1abaf0"

  # &&2
  second: "#77d7f7"

tab:
  header-message:
    enable: true
  footer-message:
    enable: true
  update:
    enable: true

    # minecraft ticks (1sec = 20ticks)
    rate: 40
  player-ping:
    enable: true

server:
  brand:
    enable: true

    update:
      enable: true
      rate: 20

  motd:
    messages:
      enable: true
  online:
    count:
      enable: true
      digit: 69
  icon:
    enable: true
    # Modes: single or random
    mode: random

    # If "single" mode is enabled, only the first one will be displayed
    names:
      - "server-icon-1"
      - "server-icon-2"

chat:
  auto-message:
    enable: false
    # if set to true, then the messages will be random
    random: false
    # minecraft ticks (1sec = 20ticks)
    period: 600

  bubble:
    enable: true
    max-per-line: 35
    read-speed: 800

  local:
    enable: true
    range: 100

    no-recipients:
      enable: true

    set-cancelled: true

  global:
    enable: true
    prefix:
      cleared: true

    set-cancelled: false

  # list of blacklisted words can be found in swears.yml
  swear-protection:
    enable: false

  patterns:
    - ":) , ☺"
    - ":D , ☻"
    - ":( , ☹"
    - ":ok: , 🖒"
    - ":+1: , 🖒"
    - ":-1: , 🖓"
    - ":cool: , 😎"
    - "B) , 😎"
    - ":clown: , 🤡"
    - "<3 , ❤"
    - "xd , 😆"
    - "%) , 😵"
    - "=D , 😃"
    - ">:( , 😡"
    - ":idk: , ¯\\_(ツ)_/¯"
    - ":angry: , (╯°□°)╯︵ ┻━┻"
    - ":happy: , ＼(＾O＾)／"

  anvil-formatting:
    # permission: flectonechat.chat.anvil-formatting
    enable: true
  book-formatting:
    # permission: flectonechat.chat.book-formatting
    enable: true
  sign-formatting:
    # permission: flectonechat.chat.sign-formatting
    enable: true

  cords:
    # permission: flectonechat.chat.cords
    enable: true

  stats:
    # permission: flectonechat.chat.stats
    enable: true

  url:
    # permission: flectonechat.chat.url
    enable: true

  tooltip:
    # permission: flectonechat.chat.tooltip
    enable: true

  ping:
    # permission: flectonechat.chat.ping
    enable: true

  markdown-||:
    # hide
    # permission: flectonechat.chat.markdown-||
    enable: true

  markdown-**:
    # bold
    # permission: flectonechat.chat.markdown-**
    enable: true

  markdown-##:
    # italic
    # permission: flectonechat.chat.markdown-##
    enable: true

  markdown-__:
    # underline
    # permission: flectonechat.chat.markdown-__
    enable: true

  markdown-??:
    # obfuscate
    # permission: flectonechat.chat.markdown-??
    enable: true

  markdown-~~:
    # strikethrough
    # permission: flectonechat.chat.markdown-~~
    enable: true

death:
  message:
    enable: true

    # if disabled, custom death messages will not be shown
    visible: true

    # if enabled, then death from any mob will be located on the "death.mob.default",
    # otherwise it will be necessary to register for each separately
    mob-default: true

advancement:
  message:
    enable: true

    task:
      visible: true
    goal:
      visible: true
    challenge:
      visible: true


player:
  display-name: "<world_prefix><vault_prefix><stream_prefix><player><afk_suffix><vault_suffix>"
  tab-name: "<world_prefix><vault_prefix><stream_prefix><player><afk_suffix><vault_suffix>"

  world:
    # type or name
    # if mode=name the language file should contain lines with names of the worlds
    mode: "type"
    prefix:
      enable: true

  name-tag:
    enable: true

  name-visible: false

  item:
    sign:
      enable: true

  join:
    message:
      enable: true

  quit:
    message:
      enable: true

command:
  afk:
    enable: true
    timeout:
      enable: true
      time: 3000

  kick:
    enable: true
    announce: true

  warn:
    enable: true
    announce: true
    count-for-ban: 3

  warnlist:
    enable: true
    per-page: 4

  unwarn:
    enable: true

  spy:
    enable: true

  ball:
    enable: true
    global: true

  banlist:
    enable: true
    per-page: 4

  broadcast:
    enable: true

  switch-chat:
    enable: true

  chat-settings:
    enable: true

  chatcolor:
    enable: true

  clear-chat:
    enable: true

  firstonline:
    enable: true

  flectonechat:
    enable: true

  helper:
    enable: true
    see:
      permission: "flectonechat.helpersee"

  ignore:
    enable: true

  ignorelist:
    enable: true
    per-page: 4

  lastonline:
    enable: true

  mail:
    enable: true

  mail-clear:
    enable: true

  maintenance:
    enable: true
    permission: "flectonechat.maintenance"
    turn-on: false

  mark:
    enable: true
    item: "WOODEN_SWORD"
    range: 30

  me:
    enable: true
    global: true

  msg:
    enable: true

  mute:
    enable: true
    announce: true

  mutelist:
    enable: true
    per-page: 4

  ping:
    enable: true
    bad:
      color: "#ff4e4e"
      count: 200
    medium:
      color: "#fce303"
      count: 100
    good:
      color: "#4eff52"

  poll:
    enable: true
    time: 50
    permission: "flectonechat.pollcreate"

  reply:
    enable: true

  stream:
    enable: true
    global: true

    offline-prefix:
      enable: true

  tempban:
    enable: true
    announce: true

  tic-tac-toe:
    enable: true

  try:
    enable: true
    global: true

  try-cube:
    enable: true
    global: true
    max-amount: 9

  unban:
    enable: true

  unmute:
    enable: true

cool-down:
  enable: false

  kick:
    enable: false
    time: 5
    permission: "flectonechat.kick.cooldown.immune"
  warn:
    enable: false
    time: 5
    permission: "flectonechat.warn.cooldown.immune"
  unwarn:
    enable: false
    time: 5
    permission: "flectonechat.unwarn.cooldown.immune"
  warnlist:
    enable: false
    time: 5
    permission: "flectonechat.warnlist.cooldown.immune"
  spy:
    enable: false
    time: 5
    permission: "flectonechat.spy.cooldown.immune"
  poll:
    enable: false
    time: 5
    permission: "flectonechat.poll.cooldown.immune"
  broadcast:
    enable: false
    time: 5
    permission: "flectonechat.broadcast.cooldown.immune"
  unban:
    enable: false
    permission: "flectonechat.ban.cooldown.immune"
  tempban:
    enable: false
    time: 5
    permission: "flectonechat.ban.cooldown.immune"
  clear-chat:
    enable: true
    time: 5
    permission: "flectonechat.clear-chat.cooldown.immune"
  switch-chat:
    enable: true
    time: 5
    permission: "flectonechat.switch-chat.cooldown.immune"
  chat-settings:
    enable: true
    time: 5
    permission: "flectonechat.chat-settings.cooldown.immune"
  localchat:
    enable: true
    time: 5
    permission: "flectonechat.localchat.cooldown.immune"
  globalchat:
    enable: true
    time: 5
    permission: "flectonechat.globalchat.cooldown.immune"
  chatcolor:
    enable: false
    time: 5
    permission: "flectonechat.chatcolor.cooldown.immune"
  flectonechat:
    enable: false
    time: 5
    permission: "flectonechat.flectonechat.cooldown.immune"
  ignore:
    enable: false
    time: 5
    permission: "flectonechat.ignore.cooldown.immune"
  ignorelist:
    enable: false
    time: 5
    permission: "flectonechat.ignorelist.cooldown.immune"
  mail:
    enable: true
    time: 5
    permission: "flectonechat.mail.cooldown.immune"
  helper:
    enable: true
    time: 5
    permission: "flectonechat.helper.cooldown.immune"
  mark:
    enable: false
    time: 5
    permission: "flectonechat.mark.cooldown.immune"
  me:
    enable: true
    time: 5
    permission: "flectonechat.me.cooldown.immune"
  msg:
    enable: false
    time: 5
    permission: "flectonechat.msg.cooldown.immune"
  ping:
    enable: false
    time: 5
    permission: "flectonechat.ping.cooldown.immune"
  reply:
    enable: false
    time: 5
    permission: "flectonechat.reply.cooldown.immune"
  mail-clear:
    enable: false
    time: 5
    permission: "flectonechat.mail-clear.cooldown.immune"
  stream:
    enable: false
    time: 5
    permission: "flectonechat.stream.cooldown.immune"
  try:
    enable: true
    time: 5
    permission: "flectonechat.try.cooldown.immune"
  try-cube:
    enable: true
    time: 5
    permission: "flectonechat.try-cube.cooldown.immune"
  afk:
    enable: false
    time: 5
    permission: "flectonechat.afk.cooldown.immune"
  mute:
    enable: false
    time: 5
    permission: "flectonechat.mute.cooldown.immune"
  unmute:
    enable: false
    time: 5
    permission: "flectonechat.mute.cooldown.immune"
  maintenance:
    enable: false
    time: 5
    permission: "flectonechat.maintenance.cooldown.immune"
  ball:
    enable: false
    time: 5
    permission: "flectonechat.ball.cooldown.immune"
  tic-tac-toe:
    enable: false
    time: 5
    permission: "flectonechat.tic-tac-toe.cooldown.immune"
  banlist:
    enable: false
    time: 5
    permission: "flectonechat.banlist.cooldown.immune"
  mutelist:
    enable: false
    time: 5
    permission: "flectonechat.mutelist.cooldown.immune"

# Sound type format
# SOUND_NAME:VOLUME:PITCH
sound:
  auto-message:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  swear:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  kick:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  warn:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  unwarn:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  warnlist:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  spy:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  poll:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  broadcast:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  unban:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  tempban:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  clear-chat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  switch-chat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  chat-settings:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  localchat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  globalchat:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  chatping:
    enable: true
    type: "BLOCK_NOTE_BLOCK_HARP:1:1"
  join:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  quit:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  chatcolor:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  flectonechat:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  ignore:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  ignorelist:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  mail:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  helper:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  mark:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  me:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  msg:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  ping:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  reply:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  mail-clear:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  stream:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  try:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  try-cube:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  afk:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  mute:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  unmute:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  maintenance:
    enable: true
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  ball:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"
  tic-tac-toe:
    enable: false
    type: "BLOCK_NOTE_BLOCK_BELL:1:1"