#  █▀ █   ██▀ ▄▀▀ ▀█▀ ▄▀▄ █▄ █ ██▀ ▄▀▀ █▄█ ▄▀▄ ▀█▀
#  █▀ █▄▄ █▄▄ ▀▄▄  █  ▀▄▀ █ ▀█ █▄▄ ▀▄▄ █ █ █▀█  █
language: en

# This is &&1
color.first: "#1abaf0"
# This is &&2
color.second: "#77d7f7"

tab.header.enable: true
tab.footer.enable: true

color.worlds.enable: true
color.normal: "#4eff52● &f"
color.nether: "#ff4e4e● &f"
color.the_end: "#834eff● &f"
color.custom: "#1abaf0● &f"

server.motd.enable: true
server.online.enable: true
server.online.number: 69

chat.ping.prefix: "@"
chat.no_recipients.enable: true
chat.color.url: "&&1"
chat.color.tooltip: "&&2[<tooltip>]"

afk.suffix: " #f2d40f💤"
afk.timeout.enable: true
afk.timeout.time: 3000

## █ █ ▄▀▄ █ █ █   ▀█▀   ▄▀▄ █▀▄ █
## ▀▄▀ █▀█ ▀▄█ █▄▄  █    █▀█ █▀  █
vault.prefix: "<vault_prefix>"
vault.suffix: "<vault_suffix>"

tab.update.enable: true
# is specified in seconds
tab.update.rate: 2

chat.locale.range: 100
chat.locale.message: "&&1<player>&&2: "

chat.global.prefix: "!"
chat.global.message: "&&1<player>&&2 » "
chat.global.enable: true

stream.prefix: "#ff4e4e⏻ "

ping.bad.color: "#ff4e4e"
ping.bad.count: 200
ping.medium.color: "#fce303"
ping.medium.count: 100
ping.good.color: "#4eff52"

mark.enable: true
mark.item: "WOODEN_SWORD"
mark.range: 30

try-cube.max_amount: 10
try-cube.6: "⚅"
try-cube.5: "⚄"
try-cube.4: "⚃"
try-cube.3: "⚂"
try-cube.2: "⚁"
try-cube.1: "⚀"

cooldown.enable: false

localechat.cooldown.enable: true
localechat.cooldown.time: 5
localechat.cooldown.permission: "flectonechat.localechat.cooldown.immune"

globalchat.cooldown.enable: true
globalchat.cooldown.time: 5
globalchat.cooldown.permission: "flectonechat.globalchat.cooldown.immune"

chatcolor.cooldown.enable: false
chatcolor.cooldown.time: 5
chatcolor.cooldown.permission: "flectonechat.chatcolor.cooldown.immune"

flectonechat.cooldown.enable: false
flectonechat.cooldown.time: 5
flectonechat.cooldown.permission: "flectonechat.flectonechat.cooldown.immune"

ignore.cooldown.enable: false
ignore.cooldown.time: 5
ignore.cooldown.permission: "flectonechat.ignore.cooldown.immune"

ignore-list.cooldown.enable: false
ignore-list.cooldown.time: 5
ignore-list.cooldown.permission: "flectonechat.ignore-list.cooldown.immune"

mail.cooldown.enable: true
mail.cooldown.time: 5
mail.cooldown.permission: "flectonechat.mail.cooldown.immune"

mark.cooldown.enable: true
mark.cooldown.time: 5
mark.cooldown.permission: "flectonechat.mark.cooldown.immune"

me.cooldown.enable: true
me.cooldown.time: 5
me.cooldown.permission: "flectonechat.me.cooldown.immune"

msg.cooldown.enable: true
msg.cooldown.time: 5
msg.cooldown.permission: "flectonechat.msg.cooldown.immune"

ping.cooldown.enable: false
ping.cooldown.time: 5
ping.cooldown.permission: "flectonechat.ping.cooldown.immune"

reply.cooldown.enable: true
reply.cooldown.time: 5
reply.cooldown.permission: "flectonechat.reply.cooldown.immune"

mail-clear.cooldown.enable: false
mail-clear.cooldown.time: 5
mail-clear.cooldown.permission: "flectonechat.mail-clear.cooldown.immune"

stream.cooldown.enable: true
stream.cooldown.time: 5
stream.cooldown.permission: "flectonechat.stream.cooldown.immune"

try.cooldown.enable: true
try.cooldown.time: 5
try.cooldown.permission: "flectonechat.try.cooldown.immune"

try-cube.cooldown.enable: true
try-cube.cooldown.time: 5
try-cube.cooldown.permission: "flectonechat.try-cube.cooldown.immune"

afk.cooldown.enable: false
afk.cooldown.time: 5
afk.cooldown.permission: "flectonechat.afk.cooldown.immune"

mute.cooldown.enable: false
mute.cooldown.time: 5
mute.cooldown.permission: "flectonechat.mute.cooldown.immune"

unmute.cooldown.enable: false
unmute.cooldown.time: 5
unmute.cooldown.permission: "flectonechat.mute.cooldown.immune"