name: FlectoneChat
version: '${project.version}'
main: net.flectone.Main
api-version: 1.16
authors: [ TheFaser ]
softdepend: [ Vault, PlaceHolderAPI, voicechat]
commands:
  ignore:
    usage: /ignore <player>
    permission: flectonechat.ignore

  ignore-list:
    usage: /ignore-list
    permission: flectonechat.ignore-list

  msg:
    usage: /msg <player> <message>
    aliases: [ w, tell, message, send ]
    permission: flectonechat.msg

  try-cube:
    usage: /try-cube <number>
    aliases: [ dice ]
    permission: flectonechat.try-cube

  try:
    usage: /try <message>
    permission: flectonechat.try

  reply:
    usage: /r <message>
    aliases: [ r ]
    permission: flectonechat.reply

  me:
    usage: /me <message>
    permission: flectonechat.me

  chatcolor:
    usage: /chatcolor <first color> <second color>
    permission: flectonechat.chatcolor

  flectonechat:
    usage: /flectonechat reload/config/locale
    aliases: [ fc ]
    permission: flectonechat.reload

  stream:
    usage: /stream start/end
    permission: flectonechat.stream

  ping:
    usage: /ping <player>
    aliases: [ p ]
    permission: flectonechat.ping

  mark:
    usage: /mark
    aliases: [ f, m ]
    permission: flectonechat.mark

  firstonline:
    usage: /firstonline <player>
    aliases: [ fonline ]
    permission: flectonechat.firstonline

  lastonline:
    usage: /lastonline <player>
    aliases: [ lonline ]
    permission: flectonechat.lastonline

  mail:
    usage: /mail <player> <message>
    permission: flectonechat.mail

  mail-clear:
    usage: /mail-clear <player> <number>
    permission: flectonechat.mail-clear

  afk:
    usage: /afk
    permission: flectonechat.afk

  mute:
    usage: /mute <player> <time> <reason>
    permission: flectonechat.mute

  unmute:
    usage: /unmute <player>
    permission: flectonechat.mute

  helper:
    usage: /helper <message>
    permission: flectonechat.helper

  technical-works:
    usage: /technical-works on/off
    permission: flectonechat.technical-works

  switch-chat:
    usage: /switch-chat local/global
    aliases: [ chat ]
    permission: flectonechat.switch-chat

  ball:
    usage: /ball <message>
    permission: flectonechat.ball

  tic-tac-toe:
    usage: /tic-tac-toe <player>
    aliases: [ ttt ]
    permission: flectonechat.tic-tac-toe

  clear-chat:
    usage: /clearchat
    permission: flectonechat.clear-chat

  tempban:
    usage: /tempban <player> <time> <reason>
    aliases: [ ban, tban ]
    permission: flectonechat.ban

  unban:
    usage: /unban <player>
    aliases: [ pardon ]
    permission: flectonechat.ban

permissions:
  flectonechat.reload:
    default: op
  flectonechat.ignore:
    default: true
  flectonechat.ignore-list:
    default: true
  flectonechat.msg:
    default: true
  flectonechat.try:
    default: true
  flectonechat.try-cube:
    default: true
  flectonechat.reply:
    default: true
  flectonechat.me:
    default: true
  flectonechat.chatcolor:
    default: true
  flectonechat.stream:
    default: op
  flectonechat.ping:
    default: true
  flectonechat.mark:
    default: true
  flectonechat.firstonline:
    default: true
  flectonechat.lastonline:
    default: true
  flectonechat.mail:
    default: true
  flectonechat.mail-clear:
    default: true
  flectonechat.afk:
    default: true
  flectonechat.mute:
    default: op
  flectonechat.helper:
    default: true
  flectonechat.technical-works:
    default: op
  flectonechat.switch-chat:
    default: true
  flectonechat.ball:
    default: true
  flectonechat.tic-tac-toe:
    default: true
  flectonechat.clear-chat:
    default: true
  flectonechat.ban:
    default: op