name: FlectoneChat
version: '${version}'
main: net.flectone.chat.FlectoneChat
api-version: '1.16'
authors: [ TheFaser, fxd ]
website: https://chat.flectone.net/
softdepend: [ DiscordSRV, PlaceholderAPI, InteractiveChat, LuckPerms, SuperVanish, Vault, PlasmoVoice, voicechat ]

permissions:

  flectonechat.chat-bubble:
    default: true
  flectonechat.extra.item-sign:
    default: true
  flectonechat.extra.item-sign.unsign:
    default: true
  flectonechat.extra.knocking:
    default: true
  flectonechat.extra.knocking.door:
    default: true
  flectonechat.extra.knocking.glass:
    default: true
  flectonechat.extra.mark:
    default: true
  flectonechat.extra.spit:
    default: true
  flectonechat.player.afk-timeout:
    default: true
  flectonechat.player.hover:
    default: true
  flectonechat.player.name.prefix:
    default: true
  flectonechat.player.name.suffix:
    default: true
  flectonechat.player.name.real:
    default: true
  flectonechat.player.name.display:
    default: true
  flectonechat.player.name.tab:
    default: true
  flectonechat.player.name-tag.sort:
    default: true
  flectonechat.player.name-tag.visible:
    default: true
  flectonechat.player.right-click:
    default: true
  flectonechat.player.world:
    default: true
  flectonechat.player-message.anvil:
    default: true
  flectonechat.player-message.book:
    default: true
  flectonechat.player-message.chat:
    default: true
  flectonechat.player-message.chat.local:
    default: true
  flectonechat.player-message.chat.global:
    default: true
  flectonechat.player-message.colors:
    default: op
  flectonechat.player-message.placeholders:
    default: op
  flectonechat.player-message.formatting:
    default: true
  flectonechat.player-message.formatting.ping:
    default: true
  flectonechat.player-message.formatting.cords:
    default: true
  flectonechat.player-message.formatting.stats:
    default: true
  flectonechat.player-message.formatting.url:
    default: true
  flectonechat.player-message.formatting.item:
    default: true
  flectonechat.player-message.formatting.mention:
    default: true
  flectonechat.player-message.formatting.markdown-||:
    default: true
  flectonechat.player-message.formatting.markdown-**:
    default: true
  flectonechat.player-message.formatting.markdown-##:
    default: true
  flectonechat.player-message.formatting.markdown-__:
    default: true
  flectonechat.player-message.formatting.markdown-??:
    default: true
  flectonechat.player-message.formatting.markdown-~~:
    default: true
  flectonechat.player-message.patterns:
    default: true
  flectonechat.player-message.sign:
    default: true
  flectonechat.player-message.swear-protection:
    default: true
  flectonechat.player-message.swear-protection.bypass:
    default: op
  flectonechat.server.brand:
    default: true
  flectonechat.server.tab.header:
    default: true
  flectonechat.server.tab.footer:
    default: true
  flectonechat.server.tab.player-list-name:
    default: true
  flectonechat.server-message.advancement:
    default: true
  flectonechat.server-message.death:
    default: true
  flectonechat.server-message.join:
    default: true
  flectonechat.server-message.quit:
    default: true
  flectonechat.sounds:
    default: true
  flectonechat.server.status.player-count.bypass:
    default: op
  flectonechat.commands.afk:
    default: true
  flectonechat.commands.ball:
    default: true
  flectonechat.commands.ban:
    default: op
  flectonechat.commands.banlist:
    default: op
  flectonechat.commands.me:
    default: true
  flectonechat.commands.broadcast:
    default: op
  flectonechat.commands.chatcolor.other:
    default: op
  flectonechat.commands.chatcolor:
    default: true
  flectonechat.commands.chatsettings:
    default: true
  flectonechat.commands.chatsettings.advancement:
    default: true
  flectonechat.commands.chatsettings.death:
    default: true
  flectonechat.commands.chatsettings.join:
    default: true
  flectonechat.commands.chatsettings.quit:
    default: true
  flectonechat.commands.chatsettings.auto-message:
    default: true
  flectonechat.commands.chatsettings.me:
    default: true
  flectonechat.commands.chatsettings.try:
    default: true
  flectonechat.commands.chatsettings.dice:
    default: true
  flectonechat.commands.chatsettings.ball:
    default: true
  flectonechat.commands.chatsettings.ban:
    default: true
  flectonechat.commands.chatsettings.mute:
    default: true
  flectonechat.commands.chatsettings.warn:
    default: true
  flectonechat.commands.chatsettings.tell:
    default: true
  flectonechat.commands.chatsettings.reply:
    default: true
  flectonechat.commands.chatsettings.mail:
    default: true
  flectonechat.commands.chatsettings.tictactoe:
    default: true
  flectonechat.commands.chatsettings.kick:
    default: true
  flectonechat.commands.chatsettings.local:
    default: true
  flectonechat.commands.chatsettings.global:
    default: true
  flectonechat.commands.chatsettings.default:
    default: true
  flectonechat.commands.clearchat:
    default: true
  flectonechat.commands.clearchat.other:
    default: op
  flectonechat.commands.firstonline:
    default: true
  flectonechat.commands.flectonechat:
    default: op
  flectonechat.commands.helper:
    default: true
  flectonechat.commands.helper.other:
    default: op
  flectonechat.commands.ignore:
    default: true
  flectonechat.commands.ignorelist:
    default: true
  flectonechat.commands.kick:
    default: op
  flectonechat.commands.lastonline:
    default: true
  flectonechat.commands.mail:
    default: true
  flectonechat.commands.clearmail:
    default: true
  flectonechat.commands.maintenance:
    default: op
  flectonechat.commands.mark:
    default: true
  flectonechat.commands.tell:
    default: true
  flectonechat.commands.mute:
    default: op
  flectonechat.commands.mutelist:
    default: op
  flectonechat.commands.ping:
    default: true
  flectonechat.commands.poll:
    default: true
  flectonechat.commands.poll.create:
    default: op
  flectonechat.commands.reply:
    default: true
  flectonechat.commands.spit:
    default: true
  flectonechat.commands.spy:
    default: op
  flectonechat.commands.stream:
    default: false
  flectonechat.commands.tictactoe:
    default: true
  flectonechat.commands.translateto:
    default: true
  flectonechat.commands.try:
    default: true
  flectonechat.commands.dice:
    default: true
  flectonechat.commands.unban:
    default: op
  flectonechat.commands.unmute:
    default: op
  flectonechat.commands.warn:
    default: op
  flectonechat.commands.unwarn:
    default: op
  flectonechat.commands.warnlist:
    default: op
  flectonechat.commands.geolocate:
    default: op