name: FlectoneChat
version: '${project.version}'
main: ru.flectone.Main
api-version: 1.16
authors: [ TheFaser ]
softdepend: [ Vault ]
commands:
  ignore:
    usage: /ignore <player>
    permission: flectonechat.ignore

  ignore-list:
    usage: /ignore-list
    permission: flectonechat.ignore-list

  msg:
    usage: /msg <player> <message>
    aliases: [ w, tell, message, send ]
    permission: flectonechat.msg

  try-cube:
    usage: /try-cube <number>
    permission: flectonechat.try-cube

  try:
    usage: /try <message>
    permission: flectonechat.try

  reply:
    usage: /r <message>
    aliases: [ r ]
    permission: flectonechat.reply

  me:
    usage: /me <message>
    permission: flectonechat.me

  chatcolor:
    usage: /chatcolor <first color> <second color>
    permission: flectonechat.chatcolor

  flectonechat:
    usage: /flectonechat reload/config/locale
    aliases: [ fc ]
    permission: flectonechat.reload

  stream:
    usage: /stream start/end
    permission: flectonechat.stream

  ping:
    usage: /ping <player>
    aliases: [ p ]
  mark:
    usage: /mark
    aliases: [ f, m ]
  firstonline:
    usage: /firstonline <player>
    aliases: [ fonline ]
  lastonline:
    usage: /lastonline <player>
    aliases: [ lonline ]

permissions:
  flectonechat.reload:
    default: op
  flectonechat.ignore:
    default: true
  flectonechat.ignore-list:
    default: true
  flectonechat.msg:
    default: true
  flectonechat.try:
    default: true
  flectonechat.try-cube:
    default: true
  flectonechat.reply:
    default: true
  flectonechat.me:
    default: true
  flectonechat.chatcolor:
    default: true
  flectonechat.stream:
    default: op